### ISSUE TITLE
Todo list for improving concolic mode.

### ISSUE THREAD

**Issue by BenSpencer** [cs-au-dk/Artemis#70]
I cut a lot of corners trying to get the very simplest version working on the very simplest examples.
- [x] Strategy for what to do when a constraint is unsolvable (skipping for now).
- [x] Strategy for what to do when a solution takes an unexpected path. Is this different for adding to the tree ahead or behind the current search position?
- [x] Ability to re-run the search when finished (e.g. at a lower depth limit).
- [ ] Organise my horrible code.
- [ ] Strategy to detect/handle failed tree merges.
- [x] Support string constraints.
- [x] Support naming variables by legacy numbering (currently id and name attributes supported).
- [x] What to do with multiple forms (currently we analyse the first).

Potential extensions:
- [ ] Support JQuery by using JQueryTarget
- [ ] Better architecture for matching FormFields and symbolic variables.

Examples I think we should be able to solve:
- [x] [trivial-int.html](https://github.com/cs-au-dk/Artemis/blob/feature-path-exploration/artemis-code/tests/demo/trivial-int.html)
- [x] [multi-constraint-int.html](https://github.com/cs-au-dk/Artemis/blob/feature-path-exploration/artemis-code/tests/demo/multi-constraint-int.html)
- [x] [interaction-int.html](https://github.com/cs-au-dk/Artemis/blob/feature-path-exploration/artemis-code/tests/demo/interaction-int.html)
- [x] [interaction-int-typed.html](https://github.com/cs-au-dk/Artemis/blob/feature-path-exploration/artemis-code/tests/demo/interaction-int-typed.html)
- [x] [arithmetic-int.html](https://github.com/cs-au-dk/Artemis/blob/feature-path-exploration/artemis-code/tests/demo/arithmetic-int.html)
- [x] trivial-string
- [x] concat-string
- [x] multi-constraint-string
- [x] string-length (Casper is working on this one)

Some "bigger picture" stuff:
- [x] Improve entry-point finding.
- [x] Add trace classification to the tree.
- [ ] Provide some "result", e.g. by scanning the classified tree and producing a single constraint representing a successful submission.
- [ ] Look into adding extra information to the graphs, such as the target nodes, the concrete values on each path, etc.
- [x] Mark nodes on the tree which are known to be UNSAT so we can ignore them in future.

Please add/edit whatever you come across. :)
